#!/bin/bash
g++ Test.cpp -std=c++1y -o main
if [ $? -ne 0 ]
then
    echo "Compile failed!"
    exit 1
fi
./main
gnuplot -e "set xlabel 'Displacement (m)';
			set ylabel 'Time (s)';
			plot 'plotq.dat' with lines, 'plotp.dat' with lines;
			pause -1;";
rm plotp.dat plotq.dat main
